title: Vishal Kumar
email: your-email@lpu.co.in
description: >
  Assistant Professor at Lovely Professional University.
  Research in mathematical modeling, reactionâ€“diffusion systems,
  and fluid dynamics.
url: "https://kumarvishal98032.github.io"
baseurl: ""

remote_theme: mmistakes/minimal-mistakes@4.26.2

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag

author:
  name: Vishal Kumar
  bio: Assistant Professor, Lovely Professional University
  location: India
