

remote_theme: mmistakes/minimal-mistakes@4.26.2

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag

author:
  name: Dr. Vishal Kumar
  bio: Assistant Professor, Lovely Professional University
  avatar: /profile.jpg
  location: India

# Navigation
header:
  nav: main
